stages:
- stage: Prod
  displayName: Deploy to Prod
  dependsOn: Test
  condition: succeeded()
  jobs:
  - deployment: ProdDeployment
    displayName: Deploy to Prod
    environment: 'Prod'
    strategy:
      runOnce:
        deploy:
          steps:
          # - script: |
          #     echo "Listing files in manifest folder"
          #     ls -l $(Build.SourcesDirectory)/manifests/dev
          #   displayName: Verify manifest files

          # - script: |
          #     echo "Fixing ownership for manifest files"
          #     chown -R azureuser:azureuser $(Build.SourcesDirectory)/manifests/dev
          #   displayName: Fix manifest file ownership

          - script: |
              echo "Replacing image tag for environment: $(EnvironmentName)"
              sed -i "s|image: blazorappacr.azurecr.io/blazer|image: blazorappacr.azurecr.io/blazer:$(IMAGE_TAG)|g" manifests/prod/deploy.yaml
            displayName: Replace image tag

          - task: Kubernetes@1
            displayName: Deploy to AKS (Prod)
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'AKS-Service-Connection'
              azureResourceGroup: $(AKS_RESOURCE_GROUP)
              kubernetesCluster: $(AKS_CLUSTER)
              namespace: prod
              command: apply
              useConfigurationFile: true
              configuration: manifests/prod
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'
              dockerRegistryEndpoint: 'ACR-Service-Connection'
              images: |
                $(ACR_NAME)/$(IMAGE_NAME):$(IMAGE_TAG)