stages:
- stage: Dev
  displayName: Deploy to Dev
  dependsOn: Build
  jobs:
  - deployment: DevDeployment
    displayName: Deploy to Dev
    environment: 'Dev'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Kubernetes@1
            displayName: Deploy to AKS (Dev)
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'AKS-Service-Connection'
              azureResourceGroup: $(AKS_RESOURCE_GROUP)
              kubernetesCluster: $(AKS_CLUSTER)
              namespace: dev
              command: apply
              useConfigurationFile: true
              configuration: |
                manifests/dev/deployment.yaml
                manifests/dev/service.yaml
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'
              dockerRegistryEndpoint: 'ACR-Service-Connection'
              images: |
                $(ACR_NAME)/$(IMAGE_NAME):$(IMAGE_TAG)