stages:
- stage: Dev
  displayName: Deploy to Dev
  dependsOn: Build
  jobs:
  - deployment: DevDeployment
    displayName: Deploy to Dev
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          # - script: |
          #     echo "Listing files in manifest folder"
          #     ls -l $(Build.SourcesDirectory)/manifests/dev
          #   displayName: Verify manifest files

          # - script: |
          #     echo "Fixing ownership for manifest files"
          #     chown -R azureuser:azureuser $(Build.SourcesDirectory)/manifests/dev
          #   displayName: Fix manifest file ownership

          # - script: |
          #     echo "Debug: listing files with hidden characters and current user"
          #     whoami
          #     ls -lb $(Build.SourcesDirectory)/manifests/dev
          #   displayName: Debug manifest folder

          - script: |
              echo "Replacing image tag for environment: $(EnvironmentName)"
              sed -i "s|image: blazeracr.azurecr.io/blazer|image: blazeracr.azurecr.io/blazer:$(IMAGE_TAG)|g" manifests/dev/deploy.yaml
            displayName: Replace image tag

          - task: Kubernetes@1
            displayName: Deploy to AKS (Dev)
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'AKS-Service-Connection'
              azureResourceGroup: $(AKS_RESOURCE_GROUP)
              kubernetesCluster: $(AKS_CLUSTER)
              namespace: dev
              command: apply
              useConfigurationFile: true
              configuration: manifests/dev
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'
              dockerRegistryEndpoint: 'ACR-Service-Connection'
              images: |
                $(ACR_NAME)/$(IMAGE_NAME):$(IMAGE_TAG)